# Generated by Django 2.1.1 on 2019-09-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190907_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Other_country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Other_degree',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
